### ISSUE TITLE
Changelly rates down from 2 days

### ISSUE THREAD

**Issue by MKTHINGS** [onitsoft/nexchange-open-client-react#235]
![image](https://user-images.githubusercontent.com/27106794/37854502-71fd0e74-2eeb-11e8-85d2-03a2dae74b91.png)

**Comment by Aracher17** [comment]
Could be because of CORS problem? 
Receiving this error message: 
Failed to load https://nexchange.io/exchange/rates: Redirect from 'https://nexchange.io/exchange/rates' to 'https://n.exchange/exchange/rates' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://tauschkrypto.de' is therefore not allowed access.

This would make sense as you have recently changed your domains

**Comment by MKTHINGS** [comment]
What happened?
You've requested a page on a website (changelly.com) that is on the Cloudflare network. Unfortunately, it is resolving to an IP address that is creating a conflict within Cloudflare's system.

What can I do?
If you are the owner of this website:
you should login to Cloudflare and change the DNS A records for changelly.com to resolve to a different IP address.

**Comment by murilob** [comment]
Same as @Aracher17 . n.exchange is not accepting request from *. Seems like CORS problem.

**Comment by BeOleg** [comment]
Resolved
